version: '2'
services:
  gs1:
    build: .
    privileged: true
    volumes:
      - ./persist/data:/data
      - ./persist/config/hosts:/config/hosts
      # - ./persist/config/secure-access:/var/lib/glusterd/secure-access
    ports:
      - '24007:24007'
      - '24008:24008'
      ## avoiding port ranges
      - '49152:49152'
      - '49153:49153'
      - '49154:49154'
      - '49155:49155'
      - '49156:49156'
      - '49157:49157'
      - '49158:49158'
    network_mode: "host"
    restart: always
